typography_spectrum: 0.4924
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1153
analytics:
  google: null
  facebook: null
  twitter: null
name: Jedi Executive
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Jedi Executive
description: 'leading cultures, blooming futures'
purpose: []
