name: Jedi Executive
favicon: null
layout_spectrum: 0.8510794071480632
typography_spectrum: 0.7682649840135127
title: Way of the Jedi Executive
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7394481431692839
  lightness: 0.01810038019903004
  saturation: 0.8912714212201536
  rhythmicContrast: 0.10627301316708326
purpose: []
