name: Jedi Executive
favicon: null
layout_spectrum: 0.1153
typography_spectrum: 0.4924
title: Way of the Jedi Executive
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
